export const queryKeys = {
  dashboard: {
    summary: ["dashboard", "summary"] as const,
    activities: (limit?: number) => ["dashboard", "activities", limit] as const,
    cashFlowSeries: ["dashboard", "cashFlowSeries"] as const,
  },
  accounts: {
    all: ["accounts"] as const,
    list: (filters?: Record<string, any>) => ["accounts", "list", filters] as const,
    tree: ["accounts", "tree"] as const,
    detail: (id: string) => ["accounts", "detail", id] as const,
    nextCode: ["accounts", "nextCode"] as const,
  },
  customers: {
    all: ["customers"] as const,
    list: (params?: Record<string, any>) => ["customers", "list", params] as const,
    detail: (id: string) => ["customers", "detail", id] as const,
  },
  suppliers: {
    all: ["suppliers"] as const,
    list: (params?: Record<string, any>) => ["suppliers", "list", params] as const,
    detail: (id: string) => ["suppliers", "detail", id] as const,
  },
  journalEntries: {
    all: ["journalEntries"] as const,
    list: (params?: Record<string, any>) => ["journalEntries", "list", params] as const,
    detail: (id: string) => ["journalEntries", "detail", id] as const,
  },
  salesInvoices: {
    all: ["salesInvoices"] as const,
    list: (params?: Record<string, any>) => ["salesInvoices", "list", params] as const,
    detail: (id: string) => ["salesInvoices", "detail", id] as const,
  },
  purchaseInvoices: {
    all: ["purchaseInvoices"] as const,
    list: (params?: Record<string, any>) => ["purchaseInvoices", "list", params] as const,
    detail: (id: string) => ["purchaseInvoices", "detail", id] as const,
  },
  creditNotes: {
    all: ["creditNotes"] as const,
    list: (params?: Record<string, any>) => ["creditNotes", "list", params] as const,
    detail: (id: string) => ["creditNotes", "detail", id] as const,
  },
  debitNotes: {
    all: ["debitNotes"] as const,
    list: (params?: Record<string, any>) => ["debitNotes", "list", params] as const,
    detail: (id: string) => ["debitNotes", "detail", id] as const,
  },
  payments: {
    all: ["payments"] as const,
    list: (params?: Record<string, any>) => ["payments", "list", params] as const,
    detail: (id: string) => ["payments", "detail", id] as const,
  },
  bankAccounts: {
    all: ["bankAccounts"] as const,
    list: () => ["bankAccounts", "list"] as const,
    detail: (id: string) => ["bankAccounts", "detail", id] as const,
  },
  bankTransactions: {
    all: ["bankTransactions"] as const,
    list: (params?: Record<string, any>) => ["bankTransactions", "list", params] as const,
    byAccount: (accountId: string) => ["bankTransactions", "byAccount", accountId] as const,
    unreconciled: (accountId: string) => ["bankTransactions", "unreconciled", accountId] as const,
    detail: (id: string) => ["bankTransactions", "detail", id] as const,
  },
  bankReconciliations: {
    all: ["bankReconciliations"] as const,
    list: (params?: Record<string, any>) => ["bankReconciliations", "list", params] as const,
    detail: (id: string) => ["bankReconciliations", "detail", id] as const,
  },
  assets: {
    all: ["assets"] as const,
    list: (params?: Record<string, any>) => ["assets", "list", params] as const,
    detail: (id: string) => ["assets", "detail", id] as const,
    summary: ["assets", "summary"] as const,
    depreciationSummary: ["assets", "depreciationSummary"] as const,
  },
  assetCategories: {
    all: ["assetCategories"] as const,
    list: () => ["assetCategories", "list"] as const,
    detail: (id: string) => ["assetCategories", "detail", id] as const,
  },
  budgets: {
    all: ["budgets"] as const,
    list: (params?: Record<string, any>) => ["budgets", "list", params] as const,
    detail: (id: string) => ["budgets", "detail", id] as const,
    vsActual: (id: string) => ["budgets", "vsActual", id] as const,
  },
  taxRates: {
    all: ["taxRates"] as const,
    list: () => ["taxRates", "list"] as const,
    active: ["taxRates", "active"] as const,
    detail: (id: string) => ["taxRates", "detail", id] as const,
  },
  taxGroups: {
    all: ["taxGroups"] as const,
    list: () => ["taxGroups", "list"] as const,
    active: ["taxGroups", "active"] as const,
    detail: (id: string) => ["taxGroups", "detail", id] as const,
  },
  fiscalYears: {
    all: ["fiscalYears"] as const,
    list: () => ["fiscalYears", "list"] as const,
    active: ["fiscalYears", "active"] as const,
    detail: (id: string) => ["fiscalYears", "detail", id] as const,
  },
  numberingSeries: {
    all: ["numberingSeries"] as const,
    list: () => ["numberingSeries", "list"] as const,
    next: (docType: string) => ["numberingSeries", "next", docType] as const,
  },
  costCenters: {
    all: ["costCenters"] as const,
    list: () => ["costCenters", "list"] as const,
  },
  reports: {
    generalLedger: (params?: Record<string, any>) => ["reports", "generalLedger", params] as const,
    trialBalance: (params?: Record<string, any>) => ["reports", "trialBalance", params] as const,
    profitLoss: (params?: Record<string, any>) => ["reports", "profitLoss", params] as const,
    balanceSheet: (params?: Record<string, any>) => ["reports", "balanceSheet", params] as const,
    cashFlow: (params?: Record<string, any>) => ["reports", "cashFlow", params] as const,
    salesRegister: (params?: Record<string, any>) => ["reports", "salesRegister", params] as const,
    purchaseRegister: (params?: Record<string, any>) => ["reports", "purchaseRegister", params] as const,
    customerStatement: (params?: Record<string, any>) => ["reports", "customerStatement", params] as const,
    vendorStatement: (params?: Record<string, any>) => ["reports", "vendorStatement", params] as const,
    arAging: (params?: Record<string, any>) => ["reports", "arAging", params] as const,
    apAging: (params?: Record<string, any>) => ["reports", "apAging", params] as const,
    gstr1: (params?: Record<string, any>) => ["reports", "gstr1", params] as const,
    gstr3b: (params?: Record<string, any>) => ["reports", "gstr3b", params] as const,
  },
  notifications: {
    all: ["notifications"] as const,
    list: (params?: Record<string, any>) => ["notifications", "list", params] as const,
    unreadCount: ["notifications", "unreadCount"] as const,
    unread: ["notifications", "unread"] as const,
  },
  systemLogs: {
    all: ["systemLogs"] as const,
    list: (params?: Record<string, any>) => ["systemLogs", "list", params] as const,
  },
};
